# Generated by Django 2.2.7 on 2019-12-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
